# https://zhuanlan.zhihu.com/p/387389708?utm_id=0

# XXX 40åˆ†é’Ÿå·¦å³ä¼šè‡ªåŠ¨æ–­å¼€

name: 90. ğŸš§ ssh_by_ngrok

on:
  workflow_dispatch:

jobs:
  SSH:
    runs-on: ubuntu-latest
    steps:
      # éœ€è¦åœ¨ä»“åº“ä¸­è®¾ç½® NGROK_TOKEN å’Œ USER_PASS
      - name: Debug via SSH
        uses: luchihoratiu/debug-via-ssh@v1.2
        with:
            # NGROK å‡­è¯
            NGROK_AUTH_TOKEN: ${{ secrets.NGROK_TOKEN }}
            # ç”¨äº SSH ç™»å½•
            SSH_PASS: ${{ secrets.USER_PASS }}
