# https://zhuanlan.zhihu.com/p/387389708?utm_id=0
# https://github.com/marketplace/actions/debugging-with-tmate
# https://github.com/marketplace/actions/debugging-with-ssh

# XXX 40åˆ†é’Ÿå·¦å³ä¼šè‡ªåŠ¨æ–­å¼€

name: 91. ğŸš§ ssh_by_tmate

on:
  workflow_dispatch:

jobs:
  SSH:
    runs-on: ubuntu-latest
    steps:
      # ä¿æŒ SSH é•¿è¿æ¥ touch /tmp/keepalive
      # ä¼šå¡åœ¨è¿™é‡Œç­‰å¾…é“¾æ¥ï¼Œé»˜è®¤ 15 åˆ†é’Ÿ
      # å¯ä»¥åœ¨è¿æ¥åé€šè¿‡ `touch /tmp/keepalive` ä¿æŒè¿æ¥
      - name: åˆ›å»º SSH ä¼šè¯
        uses: csexton/debugger-action@master

      # ç›¸æ¯” csexton/debugger-action@master å®‰å…¨ä¸€ç‚¹ï¼Œåªèƒ½ github ä¸Šæœ‰å¯†é’¥çš„æœºå™¨è®¿é—®
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
