name: 06. ğŸŸ¢ app_auto_bing_rewards

on:
  # ä½¿ç”¨ cron å®šæ—¶æ‰§è¡Œ
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  run_app:
    strategy:
      matrix:
        # ç§»åŠ¨ç«¯è®¾å¤‡ã€PC
        device: ["mobile", "pc"]
    uses: wordsworth-mk/github-runner/.github/workflows/21.run.yml@main
    with:
      APP: auto_bing_rewards
      WITH_3PARTY: false
      ARGS: --device ${{ matrix.device }}
      COMMIT_CHANGE: false
      SIMPLE_RUN: true

    secrets:
      MYPY_ACCESS_TOKEN: ${{ secrets.MYPY_ACCESS_TOKEN }}
