name: ğŸ app_y2dy

on:
  workflow_dispatch:

  # å®šæ—¶æ‰§è¡Œ
  schedule:
    # ä»£è¡¨å›½é™…æ ‡å‡†æ—¶é—´ï¼Œå®é™…åŒ—äº¬æ—¶é—´éœ€è¦ +8 å°æ—¶
    - cron: "30 00 * * *"

jobs:
  run:
    uses: M-Kepler/Python/.github/workflows/run.yml@master
    with:
      APP: youtu2douyin
